"""start

Revision ID: 38da51f64872
Revises: 
Create Date: 2021-07-20 19:06:15.324744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38da51f64872'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tmp_bsa')
    op.drop_table('tmp_bsb')
    op.create_index('ix_book_snap_1', 'book_snap', ['ts', 'exchange_market_id'], unique=False)
    op.create_foreign_key(None, 'book_snap', 'exchange_market', ['exchange_market_id'], ['exchange_market_id'])
    op.create_index('ix_book_snap_ask_1', 'book_snap_ask', ['book_snap_id'], unique=False)
    op.create_foreign_key(None, 'book_snap_ask', 'book_snap', ['book_snap_id'], ['book_snap_id'], ondelete='cascade')
    op.create_index('ix_book_snap_bid_1', 'book_snap_bid', ['book_snap_id'], unique=False)
    op.create_foreign_key(None, 'book_snap_bid', 'book_snap', ['book_snap_id'], ['book_snap_id'], ondelete='cascade')
    op.create_index('ix_book_snap_stat_book_snap_id_code', 'book_snap_stat', ['book_snap_id', 'code'], unique=True)
    op.create_foreign_key(None, 'book_snap_stat', 'book_snap', ['book_snap_id'], ['book_snap_id'], ondelete='cascade')
    op.create_unique_constraint(None, 'exchange', ['symbol'])
    op.create_index('ixu1', 'exchange_market', ['exchange_id', 'base_token_id', 'quote_token_id'], unique=True)
    op.create_unique_constraint(None, 'exchange_market', ['exchange_id', 'base_token_id', 'quote_token_id'])
    op.create_foreign_key(None, 'exchange_market', 'token', ['quote_token_id'], ['token_id'])
    op.create_foreign_key(None, 'exchange_market', 'exchange', ['exchange_id'], ['exchange_id'])
    op.create_foreign_key(None, 'exchange_market', 'token', ['base_token_id'], ['token_id'])
    op.create_unique_constraint(None, 'token', ['symbol'])
    op.create_index('ix_trade_exchange_market_id_trade_id', 'trade', ['exchange_market_id', 'trade_id'], unique=False)
    op.create_index('ix_trade_exchange_market_id_ts', 'trade', ['exchange_market_id', 'ts'], unique=False)
    op.create_index('ix_trade_ts_exchange_market_id', 'trade', ['ts', 'exchange_market_id'], unique=False)
    op.create_foreign_key(None, 'trade', 'exchange_market', ['exchange_market_id'], ['exchange_market_id'])
    op.create_index('ix_trade1m_dt_exchange_market_id', 'trade1m', ['dt', 'exchange_market_id'], unique=False)
    op.create_index('ix_trade1m_exchange_market_id_dt', 'trade1m', ['exchange_market_id', 'dt'], unique=False)
    op.create_foreign_key(None, 'trade1m', 'exchange_market', ['exchange_market_id'], ['exchange_market_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trade1m', type_='foreignkey')
    op.drop_index('ix_trade1m_exchange_market_id_dt', table_name='trade1m')
    op.drop_index('ix_trade1m_dt_exchange_market_id', table_name='trade1m')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_index('ix_trade_ts_exchange_market_id', table_name='trade')
    op.drop_index('ix_trade_exchange_market_id_ts', table_name='trade')
    op.drop_index('ix_trade_exchange_market_id_trade_id', table_name='trade')
    op.drop_constraint(None, 'token', type_='unique')
    op.drop_constraint(None, 'exchange_market', type_='foreignkey')
    op.drop_constraint(None, 'exchange_market', type_='foreignkey')
    op.drop_constraint(None, 'exchange_market', type_='foreignkey')
    op.drop_constraint(None, 'exchange_market', type_='unique')
    op.drop_index('ixu1', table_name='exchange_market')
    op.drop_constraint(None, 'exchange', type_='unique')
    op.drop_constraint(None, 'book_snap_stat', type_='foreignkey')
    op.drop_index('ix_book_snap_stat_book_snap_id_code', table_name='book_snap_stat')
    op.drop_constraint(None, 'book_snap_bid', type_='foreignkey')
    op.drop_index('ix_book_snap_bid_1', table_name='book_snap_bid')
    op.drop_constraint(None, 'book_snap_ask', type_='foreignkey')
    op.drop_index('ix_book_snap_ask_1', table_name='book_snap_ask')
    op.drop_constraint(None, 'book_snap', type_='foreignkey')
    op.drop_index('ix_book_snap_1', table_name='book_snap')
    op.create_table('tmp_bsb',
    sa.Column('book_snap_bid_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('book_snap_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    op.create_table('tmp_bsa',
    sa.Column('book_snap_ask_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('book_snap_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
